// Code generated by go-swagger; DO NOT EDIT.

package node

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/nyasuto/goswagger/models"
)

// GetNodesOKCode is the HTTP code returned for type GetNodesOK
const GetNodesOKCode int = 200

/*GetNodesOK successful operation

swagger:response getNodesOK
*/
type GetNodesOK struct {

	/*
	  In: Body
	*/
	Payload *models.Node `json:"body,omitempty"`
}

// NewGetNodesOK creates GetNodesOK with default headers values
func NewGetNodesOK() *GetNodesOK {

	return &GetNodesOK{}
}

// WithPayload adds the payload to the get nodes o k response
func (o *GetNodesOK) WithPayload(payload *models.Node) *GetNodesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodes o k response
func (o *GetNodesOK) SetPayload(payload *models.Node) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
