// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi OpenAPI Petstore
This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.


    Schemes:
      http
    Host: petstore.swagger.io
    BasePath: /v2
    Version: 1.0.0
    License: Apache-2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
